name: Kernel Build (MT6768)

on:
  push:
    branches:
      - genom-release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set execute permission to build_kernel.sh
        run: chmod +x build_kernel.sh

      - name: Run Kernel Build Script
        run: ./build_kernel.sh

